App - PokeapiMVC/Models/ErrorViewModel.cs
namespace PokeapiMVC.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

App - PokeapiMVC/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using PokeapiMVC.Models;

namespace PokeapiMVC.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

App - PokeapiMVC/Controllers/PokemonController.cs
using BLL.Interfaces;
using DAL.Entities;
using Microsoft.AspNetCore.Mvc;

namespace PokeapiMVC.Controllers;

public class PokemonController : Controller
{

    private readonly IPokemonService _pokemonService;

    public PokemonController(IPokemonService pokemonService)
    {
        _pokemonService = pokemonService;
    }
    
    // GET
    public async Task<IActionResult> Index()
    {
        List<PokeResult> pokemons = await _pokemonService.GetAll();
        return View(pokemons);
    }

    public async Task<IActionResult> Details(int id)
    {
        Pokemon? pokemon = await _pokemonService.GetById(id);

        if (pokemon is not null)
        {
            return View(pokemon);
        }

        return RedirectToAction("NotFound");
    }

    public IActionResult NotFound()
    {
        return View();
    }
}

App - PokeapiMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

App - PokeapiMVC/Views/Pokemon/Details.cshtml
@using DAL.Entities
@model DAL.Entities.Pokemon

<h1>@Model.id - @Model.name.Replace("-", " ")</h1>

<p>Taille : @((double)Model.height / 10) M</p>
<p>Poids : @((double)Model.weight / 10) Kg</p>

<h3>Types</h3>
<ul>
    @foreach (TypeData datas in @Model.types)
    {
        <li>@(datas.type.name.Replace("-", " "))</li>
    }
</ul>

<img src="@Model.sprites.front_default"/>

<h3>Stats</h3>
<ul>
    @foreach (StatData datas in @Model.stats)
    {
        <li>@datas.stat.name.Replace("-", " ") - @datas.base_stat</li>
    }
</ul>

<h3>Moves</h3>
<ul>
    @foreach (MoveData datas in @Model.moves)
    {
        <li>@datas.move.name.Replace("-", " ")</li>
    }
</ul>

<h3>Abilities</h3>
<ul>
    @foreach (AbilityData datas in @Model.abilities)
    {
        <li>@datas.ability.name.Replace("-", " ")</li>
    }
</ul>

App - PokeapiMVC/Views/Pokemon/Index.cshtml
@using DAL.Entities
@model List<DAL.Entities.PokeResult>

<h1>Mes Pokemons</h1>

<ol>
    
    @foreach (PokeResult pokemon in Model)
    {
        // htpp://www.tata/toto/titi
        //string[] datas = pokemon.url.Split("/")
                         
        <li>
            <a asp-controller="Pokemon" asp-action="Details" asp-route-id="@(pokemon.url.Split("/")[pokemon.url.Split("/").Length - 2])" >
                <button class="btn btn-primary">@pokemon.name.Replace("-", " ")</button>
            </a>
            
        </li>
    }
</ol>

App - PokeapiMVC/Views/Shared/NotFound.cshtml
<h1>ELEMENT NOT FOUND</h1>

App - PokeapiMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - App - PokeapiMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/PokeapiMVC.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">App - PokeapiMVC</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Pokemon" asp-action="Index">Pika Pika</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - App - PokeapiMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>